backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: blog
    label: Blog
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
